Algoritmo "Tabuada"

Var
   x , y ,i : inteiro


Inicio

   y <- 0
   x <- 0
   escreva("Deseja a tabuada para qual valor ? =")
   leia(x)
   
     // enquanto (y >= 0)e (y <= 10)faca
      //   escreval(x," x ",y," = ",i)
       //  y <- y + 1
        // i <- x * y
      //fimenquanto
   
      para i de 1 ate 10 faca
         y <- x * i
         escreval(x, "x" ,i, "=" ,y)
     fimpara



Fimalgoritmo